/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.fail;

class AppTest {
    @Test void appHasAGreeting() {
        //fail("아무튼 실패");
    }
}
